// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.0
// - protoc             v3.21.6
// source: apiecho/v1/myna.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMynaFillData = "/api.apiecho.v1.Myna/FillData"
const OperationMynaHeader = "/api.apiecho.v1.Myna/Header"
const OperationMynaStatus = "/api.apiecho.v1.Myna/Status"

type MynaHTTPServer interface {
	FillData(context.Context, *FillDataRequest) (*FillDataReply, error)
	Header(context.Context, *HeaderRequest) (*HeaderReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
}

func RegisterMynaHTTPServer(s *http.Server, srv MynaHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/header", _Myna_Header0_HTTP_Handler(srv))
	r.POST("/v1/filldata", _Myna_FillData0_HTTP_Handler(srv))
	r.GET("/v1/status", _Myna_Status0_HTTP_Handler(srv))
}

func _Myna_Header0_HTTP_Handler(srv MynaHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HeaderRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMynaHeader)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Header(ctx, req.(*HeaderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HeaderReply)
		return ctx.Result(200, reply)
	}
}

func _Myna_FillData0_HTTP_Handler(srv MynaHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FillDataRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMynaFillData)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FillData(ctx, req.(*FillDataRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FillDataReply)
		return ctx.Result(200, reply)
	}
}

func _Myna_Status0_HTTP_Handler(srv MynaHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMynaStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Status(ctx, req.(*StatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StatusReply)
		return ctx.Result(200, reply)
	}
}

type MynaHTTPClient interface {
	FillData(ctx context.Context, req *FillDataRequest, opts ...http.CallOption) (rsp *FillDataReply, err error)
	Header(ctx context.Context, req *HeaderRequest, opts ...http.CallOption) (rsp *HeaderReply, err error)
	Status(ctx context.Context, req *StatusRequest, opts ...http.CallOption) (rsp *StatusReply, err error)
}

type MynaHTTPClientImpl struct {
	cc *http.Client
}

func NewMynaHTTPClient(client *http.Client) MynaHTTPClient {
	return &MynaHTTPClientImpl{client}
}

func (c *MynaHTTPClientImpl) FillData(ctx context.Context, in *FillDataRequest, opts ...http.CallOption) (*FillDataReply, error) {
	var out FillDataReply
	pattern := "/v1/filldata"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMynaFillData))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MynaHTTPClientImpl) Header(ctx context.Context, in *HeaderRequest, opts ...http.CallOption) (*HeaderReply, error) {
	var out HeaderReply
	pattern := "/v1/header"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMynaHeader))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *MynaHTTPClientImpl) Status(ctx context.Context, in *StatusRequest, opts ...http.CallOption) (*StatusReply, error) {
	var out StatusReply
	pattern := "/v1/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMynaStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
