// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: apiecho/v1/myna.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeaderRequest) Reset() {
	*x = HeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiecho_v1_myna_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderRequest) ProtoMessage() {}

func (x *HeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiecho_v1_myna_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderRequest.ProtoReflect.Descriptor instead.
func (*HeaderRequest) Descriptor() ([]byte, []int) {
	return file_apiecho_v1_myna_proto_rawDescGZIP(), []int{0}
}

type HeaderReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HeaderReply) Reset() {
	*x = HeaderReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiecho_v1_myna_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderReply) ProtoMessage() {}

func (x *HeaderReply) ProtoReflect() protoreflect.Message {
	mi := &file_apiecho_v1_myna_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderReply.ProtoReflect.Descriptor instead.
func (*HeaderReply) Descriptor() ([]byte, []int) {
	return file_apiecho_v1_myna_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderReply) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type FillDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count   int32  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *FillDataRequest) Reset() {
	*x = FillDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiecho_v1_myna_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillDataRequest) ProtoMessage() {}

func (x *FillDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiecho_v1_myna_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillDataRequest.ProtoReflect.Descriptor instead.
func (*FillDataRequest) Descriptor() ([]byte, []int) {
	return file_apiecho_v1_myna_proto_rawDescGZIP(), []int{2}
}

func (x *FillDataRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FillDataRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FillDataReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FillDataReply) Reset() {
	*x = FillDataReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiecho_v1_myna_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillDataReply) ProtoMessage() {}

func (x *FillDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_apiecho_v1_myna_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillDataReply.ProtoReflect.Descriptor instead.
func (*FillDataReply) Descriptor() ([]byte, []int) {
	return file_apiecho_v1_myna_proto_rawDescGZIP(), []int{3}
}

var File_apiecho_v1_myna_proto protoreflect.FileDescriptor

var file_apiecho_v1_myna_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x79, 0x6e,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69,
	0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x42, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x69, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x41, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x46, 0x69, 0x6c,
	0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xc5, 0x01, 0x0a, 0x04, 0x4d,
	0x79, 0x6e, 0x61, 0x12, 0x58, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x63, 0x0a,
	0x08, 0x46, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x11, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x6c, 0x64, 0x61, 0x74, 0x61, 0x3a,
	0x01, 0x2a, 0x42, 0x2e, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68,
	0x6f, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x61, 0x70, 0x69, 0x2d, 0x65, 0x63, 0x68, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x65, 0x63, 0x68, 0x6f, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiecho_v1_myna_proto_rawDescOnce sync.Once
	file_apiecho_v1_myna_proto_rawDescData = file_apiecho_v1_myna_proto_rawDesc
)

func file_apiecho_v1_myna_proto_rawDescGZIP() []byte {
	file_apiecho_v1_myna_proto_rawDescOnce.Do(func() {
		file_apiecho_v1_myna_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiecho_v1_myna_proto_rawDescData)
	})
	return file_apiecho_v1_myna_proto_rawDescData
}

var file_apiecho_v1_myna_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_apiecho_v1_myna_proto_goTypes = []interface{}{
	(*HeaderRequest)(nil),   // 0: api.apiecho.v1.HeaderRequest
	(*HeaderReply)(nil),     // 1: api.apiecho.v1.HeaderReply
	(*FillDataRequest)(nil), // 2: api.apiecho.v1.FillDataRequest
	(*FillDataReply)(nil),   // 3: api.apiecho.v1.FillDataReply
	nil,                     // 4: api.apiecho.v1.HeaderReply.HeadersEntry
}
var file_apiecho_v1_myna_proto_depIdxs = []int32{
	4, // 0: api.apiecho.v1.HeaderReply.headers:type_name -> api.apiecho.v1.HeaderReply.HeadersEntry
	0, // 1: api.apiecho.v1.Myna.Header:input_type -> api.apiecho.v1.HeaderRequest
	2, // 2: api.apiecho.v1.Myna.FillData:input_type -> api.apiecho.v1.FillDataRequest
	1, // 3: api.apiecho.v1.Myna.Header:output_type -> api.apiecho.v1.HeaderReply
	3, // 4: api.apiecho.v1.Myna.FillData:output_type -> api.apiecho.v1.FillDataReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiecho_v1_myna_proto_init() }
func file_apiecho_v1_myna_proto_init() {
	if File_apiecho_v1_myna_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apiecho_v1_myna_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apiecho_v1_myna_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apiecho_v1_myna_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apiecho_v1_myna_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillDataReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiecho_v1_myna_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiecho_v1_myna_proto_goTypes,
		DependencyIndexes: file_apiecho_v1_myna_proto_depIdxs,
		MessageInfos:      file_apiecho_v1_myna_proto_msgTypes,
	}.Build()
	File_apiecho_v1_myna_proto = out.File
	file_apiecho_v1_myna_proto_rawDesc = nil
	file_apiecho_v1_myna_proto_goTypes = nil
	file_apiecho_v1_myna_proto_depIdxs = nil
}
